// Turkish operator-facing labels for every persisted status vocabulary the
// admin renders. The backend values stay the wire contract (filters, forms,
// tests against the API); the operator never has to read them. Unknown or
// absent values are shown as "Bilinmiyor" — never invented, never toned.

const LABELS: Record<string, string> = {
  // Workflow states
  discovered: "Keşfedildi",
  researching: "Araştırılıyor",
  normalized: "Normalize edildi",
  duplicate_check: "Kopya kontrolü",
  duplicate: "Kopya",
  idea_scoring: "Fikir puanlama",
  evidence_building: "Kanıt toplama",
  seo_research: "SEO araştırması",
  briefing: "Brif hazırlığı",
  drafting: "Taslak yazımı",
  editing: "Editör incelemesi",
  qa_review: "Kalite kontrolü",
  awaiting_human_review: "İnsan onayı bekliyor",
  approved: "Onaylandı",
  scheduled: "Planlandı",
  publishing: "Yayınlanıyor",
  published: "Yayınlandı",
  changes_requested: "Değişiklik istendi",
  approval_expired: "Onay süresi doldu",
  blocked: "Engellendi",
  rejected: "Reddedildi",
  // Opportunity disposition
  open: "Açık",
  commissioned: "Görevlendirildi",
  // Actors and origins
  operator: "Operatör",
  system: "Sistem",
  research_intake: "Araştırma girişi",
  model_assisted: "Model destekli",
  writer_engine: "Yazar motoru",
  human_upload: "İnsan yüklemesi",
  ai_generated: "Yapay zekâ üretimi",
  model_signal: "Model sinyali",
  deterministic: "Deterministik",
  // Research input roles / evidence roles
  primary_signal: "Birincil sinyal",
  supporting: "Destekleyici",
  contradicting: "Çelişen",
  context: "Bağlam",
  update_signal: "Güncelleme sinyali",
  key_fact: "Temel olgu",
  caution: "Uyarı",
  // Score band / eligibility
  strong: "Güçlü",
  moderate: "Orta",
  weak: "Zayıf",
  ineligible: "Uygun değil",
  commissionable: "Görevlendirilebilir",
  not_commissionable: "Görevlendirilemez",
  needs_operator_review: "Operatör incelemesi gerekli",
  // Inspiration / search / trend
  high: "Yüksek",
  medium: "Orta",
  low: "Düşük",
  unknown: "Bilinmiyor",
  known: "Biliniyor",
  not_applicable: "Uygulanamaz",
  produce: "İçerik üret",
  continue_research: "Araştırmaya devam et",
  eliminate: "Ele",
  human_review: "İnsan incelemesi",
  // Score components and missing signals
  recency: "Güncellik",
  audience_fit: "Hedef kitle uyumu",
  evidence_availability: "Kanıt mevcudiyeti",
  source_diversity: "Kaynak çeşitliliği",
  source_trust: "Kaynak güveni",
  competition: "Rekabet",
  search_demand: "Arama talebi",
  editorial_value: "Editoryal değer",
  seasonality: "Mevsimsellik",
  duplicate_overlap_risk: "Kopya örtüşme riski",
  policy_risk: "Politika riski",
  production_cost_estimate: "Üretim maliyeti tahmini",
  measured_search_demand: "Ölçülmüş arama talebi",
  trend_signal: "Trend sinyali",
  inspiration_signals: "İlham sinyalleri",
  single_source_risk: "Tek kaynak riski",
  // Ideas
  passed: "Geçti",
  failed: "Başarısız",
  not_checkable: "Kontrol edilemiyor",
  selected: "Seçildi",
  deselected: "Seçim kaldırıldı",
  // Evidence packs
  ready: "Hazır",
  insufficient: "Yetersiz",
  conflicted: "Çelişkili",
  material: "Önemli",
  blocking: "Engelleyici",
  major: "Önemli",
  minor: "Küçük",
  unresolved: "Çözülmedi",
  resolved_cautious_wording: "Temkinli ifadeyle çözüldü",
  resolved_needs_research: "Araştırma gerekli olarak çözüldü",
  resolved_editorial_judgment: "Editoryal kararla çözüldü",
  not_checked: "Kontrol edilmedi",
  no_known_conflict: "Bilinen çakışma yok",
  potential_conflict: "Olası çakışma",
  known_conflict: "Bilinen çakışma",
  // Briefs and claims
  draft: "Taslak",
  accepted_for_drafting: "Yazıma kabul edildi",
  superseded: "Yerine yenisi geldi",
  active: "Etkin",
  factual: "Olgusal",
  source_assertion: "Kaynak iddiası",
  observation: "Gözlem",
  inference: "Çıkarım",
  editorial_judgment: "Editoryal karar",
  instruction: "Talimat",
  statistic: "İstatistik",
  quote: "Alıntı",
  unverified: "Doğrulanmadı",
  verified: "Doğrulandı",
  disputed: "Tartışmalı",
  retracted: "Geri çekildi",
  // Generation
  idea_candidates: "Fikir adayları",
  intent_synthesis: "Niyet sentezi",
  brief_composition: "Brif oluşturma",
  evidence_organization: "Kanıt düzenleme",
  writer_draft: "Yazar taslağı",
  editor_review: "Editör incelemesi",
  succeeded: "Başarılı",
  validation_failed: "Doğrulama başarısız",
  provider_error: "Sağlayıcı hatası",
  timeout: "Zaman aşımı",
  cancelled: "İptal edildi",
  transport_error: "İletim hatası",
  rejected_by_api: "API reddetti",
  // Reviews / QA / decisions
  pass: "Geçti",
  revise: "Düzelt",
  claim_faithfulness: "İddia sadakati",
  exclusion_compliance: "Hariç tutma uyumu",
  objective_fit: "Hedef uyumu",
  clarity_style: "Açıklık ve üslup",
  uncertainty_framing: "Belirsizlik çerçevesi",
  ready_for_human_review: "İnsan incelemesine hazır",
  not_ready: "Hazır değil",
  media_needs: "Görsel ihtiyaçları",
  approval_revoked: "Onay geri alındı",
  // Draft blocks
  paragraph: "Paragraf",
  list: "Liste",
  how_to_step: "Adım",
  callout: "Vurgu kutusu",
  faq_item: "SSS maddesi",
  internal_link_need: "İç bağlantı ihtiyacı",
  media_need: "Görsel ihtiyacı",
  // Search signals
  search_volume: "Arama hacmi",
  trend: "Trend",
  serp_observation: "SERP gözlemi",
  query_set: "Sorgu seti",
  manual_intent_note: "Elle niyet notu",
  // Sources / duplicates
  official: "Resmi",
  expert: "Uzman",
  reputable: "Saygın",
  general: "Genel",
  reference_only: "Yalnızca referans",
  unique: "Benzersiz",
  related: "İlişkili",
  update_existing: "Mevcudu güncelle",
  reject: "Reddet",
  // Sources and discovery
  paused: "Duraklatıldı",
  disabled: "Devre dışı",
  editorial_site: "Editoryal site",
  competitor_site: "Rakip site",
  rss_feed: "RSS beslemesi",
  sitemap: "Site haritası",
  manual: "Elle",
  trend_provider: "Trend sağlayıcı",
  search_provider: "Arama sağlayıcı",
  feed: "Besleme",
  provider: "Sağlayıcı",
  search: "Arama",
  accepted: "Kabul edildi",
  fetched: "Getirildi",
  fetch_failed: "Getirme başarısız",
  out_of_scope: "Kapsam dışı",
  duplicate_url: "Kopya adres",
  source_not_active: "Kaynak etkin değil",
  policy: "Politika",
  invalid_url: "Geçersiz adres",
  unsupported_scheme: "Desteklenmeyen şema",
  success: "Başarılı",
  ssrf_blocked: "Güvenlik engeli (SSRF)",
  network_error: "Ağ hatası",
  too_large: "Çok büyük",
  disallowed_mime: "İzin verilmeyen içerik türü",
  redirect_limit_exceeded: "Yönlendirme sınırı aşıldı",
  robots_disallowed: "robots.txt izin vermiyor",
  robots_unavailable: "robots.txt erişilemedi",
  http_error: "HTTP hatası",
  retryable: "Yeniden denenebilir",
  terminal: "Kalıcı",
  allowed: "İzin verildi",
  disallowed: "İzin verilmedi",
  unavailable: "Erişilemedi",
  not_evaluated: "Değerlendirilmedi",
  unsupported_content: "Desteklenmeyen içerik",
  decode_error: "Kod çözme hatası",
  parse_error: "Ayrıştırma hatası",
  empty_content: "Boş içerik",
  extractor_error: "Çıkarıcı hatası",
  policy_rejected: "Politika reddetti",
  // Source purpose (roles / capabilities); trend and search share generic keys
  inspiration: "Fikir / İlham",
  turkish_editorial: "Türk editoryal",
  community_intent: "Topluluk / kullanıcı niyeti",
  competitor: "Rakip",
  taxonomy: "Taksonomi",
  community_need: "Kullanıcı ihtiyacı",
  market: "Türkiye pazar sinyali",
  visual_trend: "Görsel trend",
  // Integration provider states (agent C)
  healthy: "Bağlı",
  not_configured: "Yapılandırılmadı",
  access_required: "API erişimi gerekli",
  rate_limited: "Kota sınırında",
  degraded: "Kısıtlı",
  semrush: "Semrush",
  google_search_console: "Google Search Console",
  google_analytics: "Google Analytics 4",
  google_trends: "Google Trends",
  pinterest_trends: "Pinterest Trends",
  // Performance loop (agent E)
  insufficient_data: "Yetersiz veri",
  declining: "Düşüyor",
  volatile: "Dalgalı",
  proposed: "Karar bekliyor",
  dismissed: "Şimdilik geçildi",
  ignored: "Yoksayıldı",
  cluster_focus: "Küme odağı",
  keyword_add: "Anahtar kelime ekle",
  audience_focus: "Kitle odağı",
  theme_focus: "Tema odağı",
  measuring: "Ölçümde",
  refresh_candidate: "Güncelleme adayı",
  pinterest_pending: "Pinterest bekliyor",
  distributed: "Dağıtıldı",
  archived: "Arşivlendi",
  error: "Hata",
  guide: "Rehber",
  idea_list: "Fikir listesi",
  checklist: "Kontrol listesi",
  planning_guide: "Planlama rehberi",
  comparison: "Karşılaştırma",
  faq: "SSS",
  how_to: "Nasıl yapılır",
  // Opportunity intelligence bands, trend directions, evidence state,
  // historical outcome and enrichment provider states (agent D)
  very_high: "Çok yüksek",
  rising: "Yükseliyor",
  falling: "Düşüyor",
  stable: "Stabil",
  sufficient: "Yeterli",
  positive: "Olumlu",
  neutral: "Nötr",
  negative: "Olumsuz",
  not_requested: "Bu süreçte sorgulanmadı",
  stored: "Kayıtlı gözlem",
  no_data: "Veri yok",
  // Dashboard activity kinds
  workflow: "İş akışı",
  publication: "Yayın",
  pause: "Duraklatma",
  ai: "Yapay zekâ",
  transport: "İletim",
  // Intake run statuses, agent states and signal families (operator UI)
  running: "Çalışıyor",
  completed: "Tamamlandı",
  stopped: "Durduruldu",
  idle: "Boşta",
  historical_performance: "Konsepthane geçmiş verisi",
};

export const UNKNOWN_LABEL = "Bilinmiyor";

// Turkish label for a persisted status value; absent -> "Bilinmiyor". A
// value without a translation is humanized (underscores to spaces) rather
// than hidden, so a new backend vocabulary is still visible, never silent.
export function trLabel(value: string | null | undefined): string {
  if (value === null || value === undefined || value === "") {
    return UNKNOWN_LABEL;
  }
  return LABELS[value] ?? value.replaceAll("_", " ");
}

export function trList(values: readonly string[], empty = "Kayıt yok"): string {
  return values.length > 0 ? values.map(trLabel).join(", ") : empty;
}
